export const ADD_POKEMON_TO_TEAM = 'ADD_POKEMON_TO_TEAM';
export const REMOVE_POKEMON = 'REMOVE_POKEMON';
export const EDIT_POKEMON = 'EDIT_POKEMON';
export const CHANGE_POKEMON_ORDER = 'CHANGE_POKEMON_ORDER';
export const CHANGE_TEAM_ORDER = 'CHANGE_TEAM_ORDER';